# Generated by Django 5.2.1 on 2025-05-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='office_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Номер кабинета'),
        ),
    ]
