# Generated by Django 5.2.1 on 2025-05-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_office_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status_last_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата последнего изменения статуса'),
        ),
    ]
