# Generated by Django 5.2.1 on 2025-05-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appointment_status_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Забронировано'), ('completed', 'Завершено'), ('cancelled_by_client', 'Отменено клиентом'), ('cancelled_by_clinic', 'Отменено клиникой'), ('no_show', 'Клиент не явился')], default='booked', max_length=25, verbose_name='Статус записи'),
        ),
    ]
