# Generated by Django 5.2.1 on 2025-05-26 10:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailabilityoverride',
            options={'ordering': ['doctor', '-date', '-requested_at'], 'verbose_name': 'Запрос на изменение расписания (отгул/сокращение)', 'verbose_name_plural': 'Запросы на изменение расписания (отгулы/сокращения)'},
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailabilityoverride',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctoravailabilityoverride',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_availability_overrides', to=settings.AUTH_USER_MODEL, verbose_name='Обработал (администратор)'),
        ),
        migrations.AddField(
            model_name='doctoravailabilityoverride',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина запроса'),
        ),
        migrations.AddField(
            model_name='doctoravailabilityoverride',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата подачи запроса'),
        ),
        migrations.AddField(
            model_name='doctoravailabilityoverride',
            name='status',
            field=models.CharField(choices=[('requested', 'Запрошен'), ('approved', 'Одобрен'), ('rejected', 'Отклонен')], default='requested', max_length=10, verbose_name='Статус запроса'),
        ),
        migrations.AddField(
            model_name='doctoravailabilityoverride',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего изменения статуса'),
        ),
        migrations.AlterField(
            model_name='doctoravailabilityoverride',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания периода недоступности'),
        ),
        migrations.AlterField(
            model_name='doctoravailabilityoverride',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Доступен (должно быть False для отгулов)'),
        ),
        migrations.AlterField(
            model_name='doctoravailabilityoverride',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала периода недоступности'),
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailabilityoverride',
            unique_together={('doctor', 'date', 'start_time', 'end_time', 'status')},
        ),
    ]
