# Generated by Django 5.2.1 on 2025-05-26 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_doctoravailabilityoverride_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='applied_promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_with_this_code', to='main.promocode', verbose_name='Примененный промокод'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Итоговая цена (со скидкой)'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='price_at_booking',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена на момент бронирования (без скидки)'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled_by_client', 'cancelled_by_clinic']), _negated=True), fields=('doctor', 'start_datetime'), name='unique_doctor_active_slot_appointment'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled_by_client', 'cancelled_by_clinic']), _negated=True), fields=('client', 'start_datetime'), name='unique_client_active_slot_appointment'),
        ),
    ]
