# Generated by Django 5.2.1 on 2025-05-26 17:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_active_slot_appointment',
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_client_active_slot_appointment',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='final_price',
        ),
        migrations.AddField(
            model_name='appointment',
            name='discount_amount_applied',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Сумма примененной скидки'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='applied_promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_where_applied', to='main.promocode', verbose_name='Примененный промокод'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='price_at_booking',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена услуги на момент бронирования'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled_by_client', 'cancelled_by_clinic']), _negated=True), fields=('doctor', 'start_datetime'), name='unique_doctor_active_slot_appointment_v2'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled_by_client', 'cancelled_by_clinic']), _negated=True), fields=('client', 'start_datetime'), name='unique_client_active_slot_appointment_v2'),
        ),
    ]
