# Generated by Django 5.2.1 on 2025-05-27 18:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_appointment_unique_doctor_active_slot_appointment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_info_title', models.CharField(default='О нашей клинике', max_length=200, verbose_name='Заголовок основного блока')),
                ('main_info_text', models.TextField(verbose_name='Основной текст о компании')),
                ('history_title', models.CharField(blank=True, default='Наша история', max_length=200, verbose_name="Заголовок блока 'История'")),
                ('history_text', models.TextField(blank=True, verbose_name='Текст истории по годам')),
                ('requisites_title', models.CharField(blank=True, default='Реквизиты', max_length=200, verbose_name="Заголовок блока 'Реквизиты'")),
                ('requisites_text', models.TextField(blank=True, verbose_name='Текст реквизитов')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='URL логотипа')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL видео (например, YouTube, Vimeo)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Профиль компании',
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос / Термин')),
                ('answer', models.TextField(max_length=1000, verbose_name='Ответ / Определение')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='Дата добавления на сайт')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Меньшее число означает более высокое положение в списке', verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Вопрос-Ответ (FAQ)',
                'verbose_name_plural': 'Вопросы-Ответы (FAQ)',
                'ordering': ['display_order', '-date_added'],
            },
        ),
        migrations.CreateModel(
            name='NonDoctorStaffContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО сотрудника')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='other_staff_photos/', verbose_name='Фотография')),
                ('work_description', models.TextField(blank=True, verbose_name='Зона ответственности')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Рабочий телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Рабочий Email')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Меньшее число означает более высокое положение в списке', verbose_name="Порядок отображения на стр. 'Контакты'")),
                ('is_visible_on_contacts_page', models.BooleanField(default=True, verbose_name="Показывать на странице 'Контакты'")),
            ],
            options={
                'verbose_name': 'Контакт (не врач)',
                'verbose_name_plural': 'Контакты (не врачи)',
                'ordering': ['display_order', 'full_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['user_profile__user__last_name', 'user_profile__user__first_name'], 'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact_page_description',
            field=models.TextField(blank=True, help_text="Краткое описание роли или специализации для страницы контактов. Если не указано, можно использовать часть 'bio'.", null=True, verbose_name="Описание для страницы 'Контакты'"),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact_page_display_order',
            field=models.PositiveIntegerField(default=0, help_text='Меньшее число означает более высокое положение в списке.', verbose_name="Порядок на странице 'Контакты'"),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact_page_photo',
            field=models.ImageField(blank=True, help_text='Если не указано, можно использовать фото из UserProfile или стандартное.', null=True, upload_to='doctor_contact_photos/', verbose_name="Фото для страницы 'Контакты'"),
        ),
        migrations.AddField(
            model_name='doctor',
            name='show_on_contacts_page',
            field=models.BooleanField(default=True, verbose_name="Показывать на странице 'Контакты'"),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография/Основная специализация'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('slug', models.SlugField(help_text="Уникальная часть URL, генерируется из заголовка (например, 'novaya-statya-o-zdorovie')", unique=True, verbose_name='Slug (для URL)')),
                ('short_description', models.TextField(max_length=150, verbose_name='Краткое описание (1-2 предложения)')),
                ('full_content', models.TextField(max_length=1500, verbose_name='Полное содержание статьи')),
                ('image_url', models.URLField(blank=True, help_text='Ссылка на изображение для статьи', null=True, verbose_name='URL картинки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles_images/', verbose_name='Изображение')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Статья (Новость)',
                'verbose_name_plural': 'Статьи (Новости)',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('short_description', models.TextField(max_length=200, verbose_name='Краткое описание (для списка)')),
                ('full_description', models.TextField(max_length=1500, verbose_name='Полное описание (требования, условия, обязанности)')),
                ('salary_info', models.CharField(blank=True, max_length=100, verbose_name='Информация о зарплате')),
                ('date_posted', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации вакансии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Вакансия активна (отображается)')),
                ('contact_info', models.TextField(blank=True, help_text='Email, телефон или ссылка на форму отклика', verbose_name='Контактная информация для отклика')),
                ('doctor_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies', to='main.doctorcategory', verbose_name='Требуемая специализация врача (если применимо)')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-date_posted'],
            },
        ),
    ]
