# Generated by Django 5.2.1 on 2025-09-07 09:27

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_companyprofile_faqitem_nondoctorstaffcontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('website_url', models.URLField(help_text='Полный URL-адрес сайта партнера (например, https://example.com)', verbose_name='Ссылка на сайт')),
                ('logo', models.ImageField(help_text='Загрузите изображение логотипа', upload_to='partners_logos/', verbose_name='Логотип')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание (необязательно)')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть партнера с сайта, не удаляя его', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Компания-партнер',
                'verbose_name_plural': 'Компании-партнеры',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='full_content',
            field=models.TextField(verbose_name='Полное содержание статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=models.TextField(verbose_name='Краткое описание (1-2 предложения)'),
        ),
        migrations.AlterField(
            model_name='faqitem',
            name='answer',
            field=models.TextField(verbose_name='Ответ / Определение'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[main.validators.validate_age_18_plus], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[main.validators.validate_belarus_phone_number], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='full_description',
            field=models.TextField(verbose_name='Полное описание (требования, условия, обязанности)'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='short_description',
            field=models.TextField(verbose_name='Краткое описание (для списка)'),
        ),
    ]
