# Generated by Django 5.2.1 on 2025-09-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_partnercompany_alter_article_full_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Забронировано'), ('paid', 'Оплачено'), ('completed', 'Завершено'), ('cancelled_by_client', 'Отменено клиентом'), ('cancelled_by_clinic', 'Отменено клиникой'), ('no_show', 'Клиент не явился')], default='booked', max_length=25, verbose_name='Статус записи'),
        ),
    ]
