# Generated by Django 5.2.1 on 2025-09-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Файл сертификата (PDF, JPG, PNG)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='certificate_title',
            field=models.CharField(blank=True, default='Лицензии и сертификаты', max_length=200, verbose_name="Заголовок блока 'Сертификаты'"),
        ),
    ]
