# Generated by Django 5.2.1 on 2025-09-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_companyprofile_certificate_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='certificate_file',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='certificate_static_path',
            field=models.CharField(blank=True, help_text="Например: 'main/certificates/certificate.pdf'", max_length=255, verbose_name='Путь к файлу сертификата в папке static'),
        ),
    ]
