# Generated by Django 5.2.1 on 2025-09-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_companyprofile_certificate_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='certificate_static_path',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='certificate_text',
            field=models.TextField(blank=True, help_text='Содержимое сертификата в виде текста (можно вставить из PDF/скана после распознавания).', verbose_name='Текст сертификата'),
        ),
    ]
