# Generated by Django 5.2.1 on 2025-10-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_companyprofile_certificate_static_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text="Уникальная часть URL, генерируется из заголовка (например, 'novaya-statya-o-zdorovie')", max_length=100, unique=True, verbose_name='Slug (для URL)'),
        ),
    ]
