# Generated by Django 5.2.1 on 2025-10-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_article_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Профиль компании', 'verbose_name_plural': 'Профили компаний'},
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='certificate_text',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='certificate_title',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cert_city',
            field=models.CharField(default='г. Москва', max_length=100, verbose_name='Сертификат: Город выдачи'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cert_director_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сертификат: ФИО директора'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cert_director_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сертификат: Должность директора'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cert_footer_logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Сертификат: URL логотипа в футере'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cert_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Сертификат: Дата выдачи'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cert_licensee_activity_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сертификат (футер): Адрес осуществления деятельности'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cert_licensee_legal_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сертификат (футер): Юридический адрес'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cert_licensee_ogrn',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сертификат (футер): ОГРН'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cert_org_inn_kpp',
            field=models.CharField(blank=True, help_text="Напр., 'ИНН 7701234567/КПП 770101001'", max_length=255, verbose_name='Сертификат: ИНН/КПП'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cert_org_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сертификат: Название организации'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cert_registry_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Сертификат: Реестровый номер'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cert_seal_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Сертификат: URL изображения печати'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cert_subtitle',
            field=models.CharField(default='на осуществление медицинской деятельности', max_length=200, verbose_name='Сертификат: Подзаголовок'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='cert_title',
            field=models.CharField(default='Лицензия', help_text="Напр., 'Лицензия' или 'Свидетельство'", max_length=200, verbose_name='Сертификат: Главный заголовок'),
        ),
    ]
