# Generated by Django 5.2.1 on 2025-11-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_companyprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Рекомендуемый размер: 1200x500px', upload_to='banners/')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('link', models.URLField(blank=True, max_length=255, verbose_name='Ссылка (URL)')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Альтернативный текст (для SEO)')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['display_order'],
            },
        ),
    ]
