# Generated by Django 5.2.1 on 2025-11-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='slider_delay',
            field=models.PositiveIntegerField(default=3000, help_text='Используется значение из первого активного баннера. Рекомендуется ставить одинаковое значение для всех баннеров.', verbose_name='Задержка слайдера (мс)'),
        ),
    ]
